#!/bin/bash

# Declare test counters
declare -i tc=0
declare -i fails=0

############################################
# Function to run a single test
############################################
test() {
    tc=tc+1

    local COMMAND=$1
    local INP=$2
    local EX_OUT=$3
    local EX_ERR=$4

    # Determine expected return code
    EX_RET=1
    if [[ ! -s $EX_ERR ]]; then
        EX_RET=0
    fi

    # Run the command
    $COMMAND < $INP > test_out.txt 2> test_err.txt
    RET=$?

    # Check return code
    if [[ $RET != $EX_RET ]]; then
        echo "TC $tc Failed (Return Code)"
        echo "Returned $RET, Expected $EX_RET"
        echo "-----------"
        fails=$fails+1
        return
    fi

    # Check standard output
    DIFF=$(diff test_out.txt $EX_OUT)
    if [[ $DIFF != '' ]]; then
        echo "TC $tc Failed (Standard Output)"
        echo "$DIFF"
        echo "-----------"
        fails=$fails+1
        return
    fi

    # Check standard error
    DIFF=$(diff test_err.txt $EX_ERR)
    if [[ $DIFF != '' ]]; then
        echo "TC $tc Failed (Standard Error)"
        echo "$DIFF"
        echo "-----------"
        fails=$fails+1
        return
    fi

    echo "TC $tc Passed"
}

############################################
# Test Cases
############################################

test './special_case_coverage' './build_testing/input/inp1_special_case.txt' './build_testing/output/out1_special_case.txt' './build_testing/error/empty.txt'
test './special_case_coverage' './build_testing/input/inp2_special_case.txt' './build_testing/output/out2_special_case.txt' './build_testing/error/empty.txt'
test './special_case_coverage' './build_testing/input/inp3_special_case.txt' './build_testing/output/out3_special_case.txt' './build_testing/error/empty.txt'
test './special_case_coverage' './build_testing/input/inp4_special_case.txt' './build_testing/output/out4_special_case.txt' './build_testing/error/empty.txt'
test './special_case_coverage' './build_testing/input/inp5_special_case.txt' './build_testing/output/out5_special_case.txt' './build_testing/error/empty.txt'
test './special_case_coverage' './build_testing/input/inp6_special_case.txt' './build_testing/output/out6_special_case.txt' './build_testing/error/err6_special_case.txt'
test './special_case_coverage' './build_testing/input/inp7_special_case.txt' './build_testing/output/out7_special_case.txt' './build_testing/error/err7_special_case.txt'
test './special_case_coverage' './build_testing/input/inp8_special_case.txt' './build_testing/output/out8_special_case.txt' './build_testing/error/empty.txt'

############################################
# Clean up
############################################

rm test_out.txt test_err.txt

# Return code
exit $fails
