name: build script for blackjack.c		

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: build blackjack			
        run: make
        
      - name: game result coverage
        run: gcc -o game_result_coverage --coverage testing_game_result.c game_result.c; ./test_script_coverage; gcov game_result_coverage-game_result.c > coverage_report_game_result.txt

      - name: special case coverage
        run: gcc -o special_case_coverage --coverage special_case.c card_handler.c command_line.c testing_special_case.c; ./test_script_coverage; gcov special_case_coverage-special_case.c > coverage_report_special_case.txt

      - name: test game results
        run: ./test_script_coverage>./test_results.txt

      # Artifacts
      - name: upload blackjack			
        uses: actions/upload-artifact@v4	
        with:
          name: Blackjack			
          path: ./blackjack	

      - name: upload test results			
        uses: actions/upload-artifact@v4	
        with:
          name: Test Results			
          path: ./test_results.txt

      - name: upload game result coverage
        uses: actions/upload-artifact@v4	
        with:
          name: Game Results Coverage
          path: ./coverage_report_game_result.txt

      - name: upload special case coverage
        uses: actions/upload-artifact@v4	
        with:
          name: Special Case Coverage
          path: ./coverage_report_special_case.txt
      

          
