name: build script for blackjack.c		

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: build blackjack			
        run: make

      - name: upload binary			
        uses: actions/upload-artifact@v4	
        with:
          name: Blackjack executable		
          path: ./blackjack				

